### ISSUE TITLE
Issue with min and max

### ISSUE THREAD

**Issue by ivicaljubicic** [cohenadair/angular.number-input#5]
When min is greater then zero value is always set to max

Example:
min = 6, max = 19
If you try to input number 11 it will set it to 6 and then to 19. It triggers on-change for 1st digit and sets the value to 6 since 1<6 and then 2nd digit is 1 which which produces 61>19.

**Comment by cohenadair** [comment]
Thanks for the report, and sorry I'm replying so late; I didn't get any kind of notification and I didn't think to check. I'll fix this up as soon as I can, or if you already have, a pull request would be awesome!

Cheers!
