### ISSUE TITLE
Support for ng-change

### ISSUE THREAD

**Issue by lucasribsantos** [cohenadair/angular.number-input#8]
I need support for the ng-change attribute. Right now I'm using $scope.$watch to process changes in the ng-model value, but it doesn't seem like the right thing to do. Am I doing something wrong?

**Comment by cohenadair** [comment]
I don't think you're doing anything wrong.

I'm not an Angular wizard and I haven't used it in a while, but my understanding of `$scope.$watch` is that it's used to be triggered when something is updated, and in this case it's exactly what you want.

**Comment by lucasribsantos** [comment]
Thanks for the reply. My point is that it actually seems more appropriate to have an ng-change method rather than having to manually register a watcher, specially since the directive - in my eyes - should work just like a regular angular input.

The watcher will do for now, it's just a matter of convenience :smile:

**Comment by cohenadair** [comment]
Oh I agree, definitely. 

I do plan on making some updates this summer since I'm finally done school.  I'll be sure to add this to my list.

Cheers!
